// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9j9yCBhX9MbK1KcV8nxaJOVNWq6Mqa30',
    appId: '1:971935809948:web:4e37cd438e407226bec859',
    messagingSenderId: '971935809948',
    projectId: 'vanishlink-app',
    authDomain: 'vanishlink-app.firebaseapp.com',
    databaseURL: 'https://vanishlink-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanishlink-app.firebasestorage.app',
    measurementId: 'G-RZ5ZRLRJC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ZGUQEeZnTsmoffoH-DeEg-t5Ctet8Yw',
    appId: '1:971935809948:android:57c771e4f7426ec2bec859',
    messagingSenderId: '971935809948',
    projectId: 'vanishlink-app',
    databaseURL: 'https://vanishlink-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanishlink-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwYEPBP-SqNfluCdCb-PrIj-9Z229at3g',
    appId: '1:971935809948:ios:38223b6f0bd27ed9bec859',
    messagingSenderId: '971935809948',
    projectId: 'vanishlink-app',
    databaseURL: 'https://vanishlink-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanishlink-app.firebasestorage.app',
    iosBundleId: 'com.example.vanishLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwYEPBP-SqNfluCdCb-PrIj-9Z229at3g',
    appId: '1:971935809948:ios:38223b6f0bd27ed9bec859',
    messagingSenderId: '971935809948',
    projectId: 'vanishlink-app',
    databaseURL: 'https://vanishlink-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanishlink-app.firebasestorage.app',
    iosBundleId: 'com.example.vanishLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9j9yCBhX9MbK1KcV8nxaJOVNWq6Mqa30',
    appId: '1:971935809948:web:7de03072b0af5726bec859',
    messagingSenderId: '971935809948',
    projectId: 'vanishlink-app',
    authDomain: 'vanishlink-app.firebaseapp.com',
    databaseURL: 'https://vanishlink-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'vanishlink-app.firebasestorage.app',
    measurementId: 'G-4TMTQM42BX',
  );
}
